version: "3"
services:
    config-server:
        build:
            config-server
        deploy:
            resources:
                limits:
                    cpus: '0.5'
                    memory: 500M
                reservations:
                    cpus: '0.4'
                    memory: 300M
       
    sensor-emails-provider:
        build:
            sensor-emails-provider
        deploy:
            resources:
                limits:
                    cpus: '0.5'
                    memory: 500M
                reservations:
                    cpus: '0.4'
                    memory: 300M
     
        environment:
            - MONGO_PASSWORD=${MONGO_PASSWORD}
    sensor-range-provider:
        build:
            sensor-range-provider
        deploy:
            resources:
                limits:
                    cpus: '0.5'
                    memory: 500M
                reservations:
                    cpus: '0.4'
                    memory: 300M
       
        environment:
            - MONGO_PASSWORD=${MONGO_PASSWORD}
    admin-console:
        build:
            admin-console
        deploy:
            resources:
                limits:
                    cpus: '0.5'
                    memory: 500M
                reservations:
                    cpus: '0.4'
                    memory: 300M
      
        environment:
            - MONGO_PASSWORD=${MONGO_PASSWORD}
            - STREAM_API_SECRET=${STREAM_API_SECRET}
    analyzer:
        build:
            analyzer
        deploy:
            resources:
                limits:
                    cpus: '0.5'
                    memory: 500M
                reservations:
                    cpus: '0.4'
                    memory: 300M
        environment:
            - STREAM_API_SECRET=${STREAM_API_SECRET}
    avg-populator:
        build:
            avg-populator
        deploy:
            resources:
                limits:
                    cpus: '0.5'
                    memory: 500M
                reservations:
                    cpus: '0.4'
                    memory: 300M
        environment:
            - MONGO_PASSWORD=${MONGO_PASSWORD}
            - STREAM_API_SECRET=${STREAM_API_SECRET}
    avg-reducer:
        build:
            avg-reducer
        deploy:
            resources:
                limits:
                    cpus: '0.5'
                    memory: 500M
                reservations:
                    cpus: '0.4'
                    memory: 300M
        environment:
            - REDIS_PASSWORD=${REDIS_PASSWORD}
            - STREAM_API_SECRET=${STREAM_API_SECRET}
    email-notifier:
        build:
            email-notifier
        deploy:
            resources:
                limits:
                    cpus: '0.5'
                    memory: 500M
                reservations:
                    cpus: '0.4'
                    memory: 300M
        environment:
            - MAIL_PASSWORD=${MAIL_PASSWORD}
            - STREAM_API_SECRET=${STREAM_API_SECRET}
